/*
 * generated by Xtext 2.10.0
 */
package org.ancit.examples.xtext.validation

import org.eclipse.xtext.validation.Check
import addressbook.Contact
import addressbook.AddressbookPackage

/**
 * This class contains custom validation rules. 
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
class MyABDslValidator extends AbstractMyABDslValidator {
	
	public static val INVALID_NAME = 'invalidName'

	@Check
	def checkContactNameStartsWithCapital(Contact contact) {
		if (!Character.isUpperCase(contact.name.charAt(0))) {
			warning('Name should start with a capital', 
					AddressbookPackage.Literals.CONTACT__NAME,
					INVALID_NAME)
		}
	}
	
}
