/*
 * generated by Xtext 2.10.0
 */
package org.ancit.examples.xtext


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class MyABDslRuntimeModule extends AbstractMyABDslRuntimeModule {
}
