/*
 * generated by Xtext 2.10.0
 */
package org.ancit.examples.xtext


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class MyABDslStandaloneSetup extends MyABDslStandaloneSetupGenerated {

	def static void doSetup() {
		new MyABDslStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
