/*
 * generated by Xtext 2.10.0
 */
package org.ancit.examples.xtext.ide.contentassist.antlr;

import com.google.inject.Inject;
import java.util.Collection;
import java.util.HashMap;
import java.util.Map;
import org.ancit.examples.xtext.ide.contentassist.antlr.internal.InternalMyABDslParser;
import org.ancit.examples.xtext.services.MyABDslGrammarAccess;
import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ide.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

public class MyABDslParser extends AbstractContentAssistParser {

	@Inject
	private MyABDslGrammarAccess grammarAccess;

	private Map<AbstractElement, String> nameMappings;

	@Override
	protected InternalMyABDslParser createParser() {
		InternalMyABDslParser result = new InternalMyABDslParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getEStringAccess().getAlternatives(), "rule__EString__Alternatives");
					put(grammarAccess.getAddressBookAccess().getGroup(), "rule__AddressBook__Group__0");
					put(grammarAccess.getAddressBookAccess().getGroup_3(), "rule__AddressBook__Group_3__0");
					put(grammarAccess.getAddressBookAccess().getGroup_3_3(), "rule__AddressBook__Group_3_3__0");
					put(grammarAccess.getAddressBookAccess().getGroup_4(), "rule__AddressBook__Group_4__0");
					put(grammarAccess.getAddressBookAccess().getGroup_4_3(), "rule__AddressBook__Group_4_3__0");
					put(grammarAccess.getGroupAccess().getGroup(), "rule__Group__Group__0");
					put(grammarAccess.getGroupAccess().getGroup_4(), "rule__Group__Group_4__0");
					put(grammarAccess.getGroupAccess().getGroup_4_3(), "rule__Group__Group_4_3__0");
					put(grammarAccess.getContactAccess().getGroup(), "rule__Contact__Group__0");
					put(grammarAccess.getContactAccess().getGroup_4(), "rule__Contact__Group_4__0");
					put(grammarAccess.getContactAccess().getGroup_5(), "rule__Contact__Group_5__0");
					put(grammarAccess.getAddressBookAccess().getGroupsAssignment_3_2(), "rule__AddressBook__GroupsAssignment_3_2");
					put(grammarAccess.getAddressBookAccess().getGroupsAssignment_3_3_1(), "rule__AddressBook__GroupsAssignment_3_3_1");
					put(grammarAccess.getAddressBookAccess().getContactsAssignment_4_2(), "rule__AddressBook__ContactsAssignment_4_2");
					put(grammarAccess.getAddressBookAccess().getContactsAssignment_4_3_1(), "rule__AddressBook__ContactsAssignment_4_3_1");
					put(grammarAccess.getGroupAccess().getNameAssignment_2(), "rule__Group__NameAssignment_2");
					put(grammarAccess.getGroupAccess().getContactsAssignment_4_2(), "rule__Group__ContactsAssignment_4_2");
					put(grammarAccess.getGroupAccess().getContactsAssignment_4_3_1(), "rule__Group__ContactsAssignment_4_3_1");
					put(grammarAccess.getContactAccess().getNameAssignment_2(), "rule__Contact__NameAssignment_2");
					put(grammarAccess.getContactAccess().getAddressAssignment_4_1(), "rule__Contact__AddressAssignment_4_1");
					put(grammarAccess.getContactAccess().getEmailAssignment_5_1(), "rule__Contact__EmailAssignment_5_1");
				}
			};
		}
		return nameMappings.get(element);
	}

	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			InternalMyABDslParser typedParser = (InternalMyABDslParser) parser;
			typedParser.entryRuleAddressBook();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public MyABDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(MyABDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
