/*
 * generated by Xtext 2.10.0
 */
package org.ancit.examples.xtext.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class MyABDslAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("org/ancit/examples/xtext/parser/antlr/internal/InternalMyABDsl.tokens");
	}
}
