/*
 * generated by Xtext 2.10.0
 */
package org.ancit.examples.xtext.parser.antlr;

import com.google.inject.Inject;
import org.ancit.examples.xtext.parser.antlr.internal.InternalMyABDslParser;
import org.ancit.examples.xtext.services.MyABDslGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class MyABDslParser extends AbstractAntlrParser {

	@Inject
	private MyABDslGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalMyABDslParser createParser(XtextTokenStream stream) {
		return new InternalMyABDslParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "AddressBook";
	}

	public MyABDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(MyABDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
