/*
 * generated by Xtext 2.10.0
 */
package org.ancit.examples.xtext.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractMyABDslScopeProvider extends DelegatingScopeProvider {
}
