/*
 * generated by Xtext 2.10.0
 */
package org.ancit.examples.xtext.ui.contentassist


/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
class MyABDslProposalProvider extends AbstractMyABDslProposalProvider {
}
